version: '2'
services:
  master:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: .
    # network_mode: host
    ports:
      - "61613:61613"
      - "8161:8161"
    volumes:
      - "${PWD}/broker1/activemq.xml:/opt/activemq/conf/activemq.xml"
      - "${PWD}/broker1/log4j.properties:/opt/activemq/conf/log4j.properties"
  slave:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: .
    # network_mode: host
    ports:
      - "61614:61613"
      - "8161"
    volumes:
      - "${PWD}/broker2/activemq.xml:/opt/activemq/conf/activemq.xml"
      - "${PWD}/broker1/log4j.properties:/opt/activemq/conf/log4j.properties:ro"
  consumer:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: client  
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
    # image: ruby:2.1
    volumes:
      - ${PWD}/client:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: ruby consumer2.rb
  mcollective:
    image: puppet/puppet-agent
    entrypoint: /opt/puppetlabs/puppet/bin/mcollectived --no-daemonize
    volumes:
      - ${PWD}/mcollective/client.cfg:/etc/puppetlabs/mcollective/client.cfg:ro
      - ${PWD}/mcollective/server.cfg:/etc/puppetlabs/mcollective/server.cfg:ro