version: '2'
services:
  master:
    image: danielpalstra/activemq:master
    ports:
      - "61613:61613"
      - "8161:8161"
  slave:
    image: danielpalstra/activemq:slave  
    # network_mode: host
    ports:
      - "61614:61613"
      - "8161"
    depends_on: 
      - master
  mcollective:
    image: danielpalstra/mcollective
    command: '--no-daemonize'
    # entrypoint: /opt/puppetlabs/puppet/bin/mcollectived --no-daemonize
    depends_on: 
      - master
      - slave